import test from'node:test';import assert from'node:assert/strict';import{randomUUID}from'node:crypto';import{localStack,product,order,pay,eventually}from'../../helpers/local-stack.mjs';import{miniHarness}from'../../helpers/mini-page/harness.mjs';
test('F044 实际小程序页面连真实API：登录、支付取消/失败/权威刷新、消息已读',async(t)=>{
 const s=await localStack(t,'t011');const h=miniHarness(s);t.after(()=>h.close());
 const profile=h.page('features/profile/pages/index/index.ts');await profile.load();assert.equal(profile.data.user,null);await profile.login();await h.idle();assert.ok(profile.data.user.id);
 const a=await s.login('alice');a.address=await s.address(a.token);const p=await product(s),placed=await order(s,a,p,30),o=placed.order??placed;
 h.storage.set('pindian_user_token',a.token);const detail=h.page('features/orders/pages/detail/index.ts');detail.onLoad({id:o.id});await h.idle();assert.ok(detail.data.order,detail.data.error);assert.equal(detail.data.order.status,'unpaid');assert.equal(detail.data.amountText,'7.51');
 const hc=miniHarness(s,{payScenario:'cancel'});t.after(()=>hc.close());hc.storage.set('pindian_user_token',a.token);const cancelled=hc.page('features/orders/pages/detail/index.ts');await cancelled.load(o.id);await cancelled.initiatePay();await hc.idle();assert.equal(cancelled.data.error,'已取消支付');assert.equal(cancelled.data.order.status,'unpaid');
 const hf=miniHarness(s,{payScenario:'fail'});t.after(()=>hf.close());hf.storage.set('pindian_user_token',a.token);const failed=hf.page('features/orders/pages/detail/index.ts');await failed.load(o.id);await failed.initiatePay();await hf.idle();assert.equal(failed.data.error,'支付失败');assert.equal(failed.data.order.status,'unpaid');
 const hu=miniHarness(s,{payScenario:'success_unconfirmed'});t.after(()=>hu.close());hu.storage.set('pindian_user_token',a.token);const uncertain=hu.page('features/orders/pages/detail/index.ts');await uncertain.load(o.id);await uncertain.initiatePay();await hu.idle();assert.equal(uncertain.data.order.status,'unpaid','前端成功提示不得生成支付事实');
 await detail.initiatePay();await h.idle();assert.equal(detail.data.order.status,'paid');
 const b=await s.login('bob');const hb=miniHarness(s,{user:'bob'});t.after(()=>hb.close());hb.storage.set('pindian_user_token',b.token);const other=hb.page('features/orders/pages/detail/index.ts');await other.load(o.id);assert.equal(other.data.notFound,true);assert.equal(other.data.order,null);
 const api=h.module('platform/order-api.ts');const extra=await api.placeOrder(p.id,30,a.address.id);assert.equal(extra.status,'unpaid');assert.ok((await api.listMyOrders()).items.some(x=>x.id===extra.id));assert.equal((await api.cancelMyOrder(extra.id)).cancelled,true);
 h.failures.add('/notifications');const notices=h.page('features/notifications/pages/index/index.ts');await notices.reload();assert.ok(notices.data.error.includes('网络'));h.failures.clear();await notices.reload();assert.equal(notices.data.items.length,0);
 for(let i=0;i<2;i++)await s.db.query(`INSERT INTO notifications(recipient_user_id,event_type,title,body,idempotency_key) VALUES($1,'page-fixture','装置初态','前端测试',$2)`,[a.user.id,randomUUID()]);
 await notices.reload();assert.equal(notices.data.unreadCount,2);const tap={currentTarget:{dataset:{index:0}}};await Promise.all([notices.onTapNotice(tap),notices.onTapNotice(tap)]);assert.equal(notices.data.unreadCount,1);await notices.onTapNotice(tap);assert.equal(notices.data.unreadCount,1);await notices.reload();assert.equal(notices.data.unreadCount,1);
 await s.http('/mini/v1/auth/logout',{token:a.token,method:'POST'});await assert.rejects(()=>api.listMyOrders(),e=>e.name==='UserAuthExpiredError');assert.equal(h.storage.has('pindian_user_token'),false);await notices.reload();assert.equal(notices.data.needLogin,true);
});
