import{mkdirSync,readFileSync,writeFileSync,readdirSync,existsSync}from'node:fs';import{resolve,join}from'node:path';import{spawnSync}from'node:child_process';import{createHash}from'node:crypto';import{pathToFileURL}from'node:url';import{docker}from'./docker.mjs';import{sha}from'./backup.mjs';
function command(program,args){const r=spawnSync(program,args,{encoding:'utf8',maxBuffer:32*1024*1024});if(r.status!==0)throw Error(program+'失败：'+(r.stderr||r.error?.message));return r.stdout.trim();}
export function verifyPackage(directory){const m=JSON.parse(readFileSync(join(directory,'manifest.json'),'utf8'));if(m.version!==1||! /^[a-f0-9]{40}$/.test(m.commit)||!m.images||!m.migrations?.length||! /^[a-f0-9]{64}$/.test(m.applicationDigest)||!m.files?.['source.tar'])throw Error('发布清单非法');for(const[name,hash]of Object.entries(m.files)){if(!['source.tar','runtime-images.tar'].includes(name)||! /^[a-f0-9]{64}$/.test(hash)||sha(join(directory,name))!==hash)throw Error('发布包校验失败');}for(const image of Object.values(m.images))if(! /^sha256:[a-f0-9]{64}$/.test(image.id))throw Error('镜像ID非法');return m;}
export function loadPackageImages(directory){const m=verifyPackage(directory);if(m.files['runtime-images.tar'])docker(['load','-i',join(directory,'runtime-images.tar')],{stdio:'inherit'});for(const image of Object.values(m.images))if(docker(['image','inspect',image.id,'--format','{{.Id}}']).trim()!==image.id)throw Error('封存镜像不可用');return m;}
export function makePackage(ref='HEAD',{exportImages=true}={}){
 const commit=command('git',['rev-parse','--verify','--end-of-options',ref+'^{commit}']);if(! /^[a-f0-9]{40}$/.test(commit))throw Error('必须是有效Git提交');
 const base=resolve('data/release/packages'),dir=join(base,commit),source=join(dir,'source');if(!dir.startsWith(base+'/')&&!dir.startsWith(base+'\\'))throw Error('包路径非法');
 if(existsSync(dir)){const manifest=verifyPackage(dir);if(exportImages&&!manifest.files['runtime-images.tar']){for(const image of Object.values(manifest.images))if(docker(['image','inspect',image.tag,'--format','{{.Id}}']).trim()!==image.id)throw Error('包镜像标签已改变，禁止导出不匹配版本');const file=join(dir,'runtime-images.tar');docker(['save','-o',file,...Object.values(manifest.images).map(i=>i.tag)],{stdio:'inherit'});manifest.files['runtime-images.tar']=sha(file);writeFileSync(join(dir,'manifest.json'),JSON.stringify(manifest,null,2)+'\n');}return{directory:dir,manifest};}mkdirSync(source,{recursive:true});
 const archive=join(dir,'source.tar');command('git',['archive','--format=tar','--output='+archive,commit]);command('tar',['-xf',archive,'-C',source]);
 const apiTag='pindian-api:'+commit.slice(0,12),adminTag='pindian-admin:'+commit.slice(0,12);
 docker(['build','-f',join(source,'backend/Dockerfile'),'-t',apiTag,source],{stdio:'inherit'});docker(['build','-f',join(source,'apps/admin-web/Dockerfile'),'-t',adminTag,source],{stdio:'inherit'});
 const images={};for(const[key,tag]of Object.entries({api:apiTag,admin:adminTag,postgres:'postgres:17-alpine',gateway:'nginx:stable-alpine'}))images[key]={tag,id:docker(['image','inspect',tag,'--format','{{.Id}}']).trim()};
 const migrations=readdirSync(join(source,'backend/migrations')).filter(f=>f.endsWith('.sql')).sort().map(name=>({name,sha256:sha(join(source,'backend/migrations',name))}));
 const objects=command('git',['ls-tree','-r','--format=%(path) %(objectname)',commit,'--','backend','contracts','apps','infra/docker','infra/nginx','infra/release/nginx.conf','package.json','package-lock.json','tsconfig.base.json']);
 const applicationDigest=createHash('sha256').update(objects).digest('hex');const files={'source.tar':sha(archive)};
 if(exportImages){const bundle=join(dir,'runtime-images.tar');docker(['save','-o',bundle,...Object.values(images).map(i=>i.tag)],{stdio:'inherit'});files['runtime-images.tar']=sha(bundle);}
 const manifest={version:1,commit,createdAt:new Date().toISOString(),files,images,migrations,applicationDigest};writeFileSync(join(dir,'manifest.json'),JSON.stringify(manifest,null,2)+'\n');return{directory:dir,manifest};
}
if(process.argv[1]&&import.meta.url===pathToFileURL(resolve(process.argv[1])).href){try{const p=makePackage(process.argv[2]??'HEAD',{exportImages:!process.argv.includes('--no-images')});console.log('发布包完成：'+p.directory+'（仅已提交源码，不含运行密钥）');}catch(e){console.error(e.message);process.exitCode=1;}}
