import{readFileSync,writeFileSync,mkdirSync,existsSync}from'node:fs';import{resolve,join}from'node:path';import{pathToFileURL}from'node:url';import{verifyPackage}from'./package.mjs';import{docker,stack}from'./docker.mjs';import{validateReleaseEnvironment}from'./guards.mjs';import{validateRollback,validateMigrationCompatibility}from'./release-guards.mjs';import{verifyBackup}from'./restore.mjs';import{health}from'./health.mjs';import{tlsRequest}from'./https.mjs';async function eventually(work,timeout){const until=Date.now()+timeout;let error;do{try{if(await work())return;}catch(e){error=e;}await new Promise(r=>setTimeout(r,300));}while(Date.now()<until);throw error??Error('发布健康超时');}
export async function publish({project,envFile,directory,rehearsal=false,rollback=false,backupDirectory}){
 const m=verifyPackage(directory),s=stack(project,envFile,{rehearsal});if(rehearsal&&!/^pindian-rehearsal-source$/.test(project))throw Error('演练发布只允许本轮source');if(!rehearsal)validateReleaseEnvironment(s.env);
 const stateDir=resolve('data/release/state');mkdirSync(stateDir,{recursive:true});const stateFile=join(stateDir,project+'.json'),state=existsSync(stateFile)?JSON.parse(readFileSync(stateFile,'utf8')):null;
 if(rollback){if(!state?.current)throw Error('没有当前发布记录，不能回退');validateRollback(state.current.manifest,m);}
 const applied=s.exec('postgres','psql','-U',s.env.POSTGRES_USER,'-d',s.env.POSTGRES_DB,'-At','-c','SELECT name FROM schema_migrations ORDER BY name').trim().split(/\r?\n/).filter(Boolean);validateMigrationCompatibility(applied,m);
 if(m.migrations.some(x=>!applied.includes(x.name))){if(!backupDirectory)throw Error('存在新迁移，必须提供完整备份');const backup=verifyBackup(backupDirectory);if(backup.sourceProject!==project||JSON.stringify(backup.migrations)!==JSON.stringify(applied))throw Error('迁移前备份不匹配当前项目');}
 for(const image of Object.values(m.images))if(docker(['image','inspect',image.id,'--format','{{.Id}}']).trim()!==image.id)throw Error('本地镜像不匹配，先从已校验镜像包docker load');
 const overlay=join(stateDir,project+'-images.json');const services=Object.fromEntries(Object.entries(m.images).map(([service,image])=>[service,{image:image.id,pull_policy:'never'}]));services.worker={image:m.images.api.id,pull_policy:'never'};writeFileSync(overlay,JSON.stringify({services},null,2));
 const args=s.args.includes(overlay)?s.args:[...s.args,'-f',overlay];const before={current:state?.current??null,target:{directory:resolve(directory),manifest:m},status:'deploying',updatedAt:new Date().toISOString()};writeFileSync(stateFile,JSON.stringify(before,null,2));
 try{s.run('stop','api','worker');docker([...args,'up','-d']);
 // gateway / admin 启动时解析上游IP，应用重建后重启以刷新DNS。
 docker([...args,'restart','admin','gateway']);docker([...args,'up','-d','--wait','--wait-timeout','180']);await eventually(()=>health({project,envFile,rehearsal}),45000);
 if(rehearsal){const r=await tlsRequest(s.env.PUBLIC_API_BASE_URL+'/api/health/ready');if(r.status!==200)throw Error('发布HTTPS就绪失败');}
 const result={current:{directory:resolve(directory),manifest:m},previous:state?.current??null,status:'healthy',updatedAt:new Date().toISOString(),rollback};writeFileSync(stateFile,JSON.stringify(result,null,2));return result;
 }catch(e){writeFileSync(stateFile,JSON.stringify({...before,status:'failed',updatedAt:new Date().toISOString()},null,2));throw e;}
}
if(process.argv[1]&&import.meta.url===pathToFileURL(resolve(process.argv[1])).href){const[project,envFile,directory,...flags]=process.argv.slice(2);try{await publish({project,envFile,directory,rehearsal:flags.includes('rehearsal'),rollback:flags.includes('rollback'),backupDirectory:flags.find(x=>x.startsWith('backup='))?.slice(7)});console.log('固定image ID发布/回退及健康检查通过');}catch(e){console.error(e.message);process.exitCode=1;}}
