import test from 'node:test';import assert from 'node:assert/strict';import{createRequire}from'node:module';const require=createRequire(import.meta.url);
let ApprovalService;try{({ApprovalService}=require('../../../backend/dist/contexts/after-sales/application/approval.js'));}catch(e){if(e.code!=='MODULE_NOT_FOUND')throw e;}
const actor='aaaaaaaa-9999-4999-8999-000000000001',orderId='bbbbbbbb-9999-4999-8999-000000000001',ticketId='cccccccc-9999-4999-8999-000000000001',supervisor='dddddddd-9999-4999-8999-000000000001',user='eeeeeeee-9999-4999-8999-000000000001';
function setup(){assert.equal(typeof ApprovalService,'function','审批功能尚未实现');let ticket={state:{ticketId,userId:user,relatedOrderId:orderId,status:'processing',assignedAgentId:actor},recordRefund(id){return {...this,state:{...this.state,relatedRefundId:id}};}};const tx={},rows=new Map(),actions=[];let refunds=0,ships=0;let failAudit=false;
  const repository={findByClientKey:async(a,key)=>[...rows.values()].find(r=>r.state.requesterId===a&&r.state.clientRequestId===key)??null,insert:async r=>rows.set(r.state.id,r),findByIdForUpdate:async id=>rows.get(id)??null,save:async r=>rows.set(r.state.id,r),list:async()=>[...rows.values()]};
  const effects={validateRefund:async(_,t)=>{assert.equal(t,tx);return {amountFen:25251};},createRefund:async(_,t)=>{assert.equal(t,tx);refunds++;return {refundId:orderId};},validateReshipment:async()=>{},createReshipment:async(_,t)=>{assert.equal(t,tx);ships++;return {shipmentId:orderId};}};
  const service=new ApprovalService({requests:repository,tickets:{findByIdForUpdate:async()=>ticket,findById:async()=>ticket,save:async t=>ticket=t,insertAction:async(_,a,t)=>{assert.equal(t,tx);actions.push(a);}},effects,runner:{run:async fn=>fn(tx)},audit:{execute:async(_,t)=>{assert.equal(t,tx);if(failAudit)throw new Error('审计故障');}},clock:{now:()=>new Date('2026-10-02')}});
  const input={ticketId,orderId,kind:'refund',clientRequestId:'refund-1',reason:'商品售后',actorId:actor,payload:{}};
  return {service,input,rows,actions,setFail:()=>failAudit=true,refunds:()=>refunds,ships:()=>ships};
}
test('审批申请不直接退款，同键同内容返回原申请、异内容冲突',async()=>{const s=setup();const a=await s.service.submit(s.input),b=await s.service.submit(s.input);assert.equal(a.request.state.id,b.request.state.id);assert.equal(a.request.state.status,'pending');assert.equal(s.refunds(),0);assert.equal(s.actions.length,1);await assert.rejects(()=>s.service.submit({...s.input,reason:'不同原因'}),e=>e.code==='IDEMPOTENCY_CONFLICT');});
test('普通客服不能审核；超级管理员批准全额退款及重复恢复只执行一次',async()=>{const s=setup(),r=(await s.service.submit(s.input)).request;await assert.rejects(()=>s.service.review({requestId:r.state.id,actorId:actor,isSuperAdmin:false,decision:'approve',reason:'同意'}),e=>e.code==='FORBIDDEN');const review={requestId:r.state.id,actorId:supervisor,isSuperAdmin:true,decision:'approve',reason:'审核通过'};await s.service.review(review);await s.service.review(review);assert.equal(s.refunds(),1);assert.equal(s.rows.get(r.state.id).state.status,'executed');await assert.rejects(()=>s.service.review({...review,decision:'reject'}),e=>e.code==='APPROVAL_STATE_CONFLICT');});
test('拒绝申请不产生业务事实；工单关联和客服归属不能绕过',async()=>{const s=setup();await assert.rejects(()=>s.service.submit({...s.input,actorId:supervisor}),e=>e.code==='NOT_FOUND');await assert.rejects(()=>s.service.submit({...s.input,orderId:supervisor}),e=>e.code==='NOT_FOUND');const r=(await s.service.submit(s.input)).request;await s.service.review({requestId:r.state.id,actorId:supervisor,isSuperAdmin:true,decision:'reject',reason:'缺少凭证'});assert.equal(s.refunds(),0);assert.equal(s.rows.get(r.state.id).state.status,'rejected');});
test('补发批准使用同一审批事务，重复审核不重复创建包裹',async()=>{const s=setup();const r=(await s.service.submit({...s.input,kind:'reshipment',payload:{fulfillmentId:ticketId,quantityGrams:1,company:'顺丰',trackingNo:'TEST-1'}})).request;const input={requestId:r.state.id,actorId:supervisor,isSuperAdmin:true,decision:'approve',reason:'确认补发'};await s.service.review(input);await s.service.review(input);assert.equal(s.ships(),1);assert.equal(s.refunds(),0);});
test('审批审计错误必须向外传播，不能声称审核成功',async()=>{const s=setup(),r=(await s.service.submit(s.input)).request;s.setFail();await assert.rejects(()=>s.service.review({requestId:r.state.id,actorId:supervisor,isSuperAdmin:true,decision:'approve',reason:'同意'}),/审计故障/);});
test('补发原因在申请阶段受包裹200字存储约束，不创建无法批准的申请',async()=>{const s=setup();await assert.rejects(()=>s.service.submit({...s.input,kind:'reshipment',reason:'原'.repeat(201),payload:{fulfillmentId:ticketId,quantityGrams:1,company:'顺丰',trackingNo:'TEST-LONG'}}),e=>e.code==='VALIDATION_FAILED');assert.equal(s.rows.size,0);});
